### ISSUE TITLE
v.0.8.0 Failed to write to trie: Database missing expected key: <...> Hash not equal

### ISSUE THREAD

**Issue by ensrationis** [airalab/substrate-node-robonomics#13]
```
2019-03-13 10:26:56 Failed to write to trie: Database missing expected key: 0x8b9689865ec389991881ee5ae1d09e570fd16ce131e0fbf1c0c9cd5ed2645579
Hash not equal
e7e293aa419c0e8370e63ae4e0ed7134f24462889c8cdaea4be15d6513fa46f1
9a18b9b3ce229634c1e7b615b7b8a2bac357503bef68c495079dbbe4c882f399
/home/akru/.cargo/git/checkouts/substrate-7e08433d4c370a21/4cbda5d/srml/executive/src/lib.rs
214
3
2019-03-13 10:26:57 Failed to write to trie: Database missing expected key: 0x8b9689865ec389991881ee5ae1d09e570fd16ce131e0fbf1c0c9cd5ed2645579
Hash: given=e7e293aa419c0e8370e63ae4e0ed7134f24462889c8cdaea4be15d6513fa46f1, expected=9a18b9b3ce229634c1e7b615b7b8a2bac357503bef68c495079dbbe4c882f399

====================

stack backtrace:
   0: substrate_panic_handler::set::{{closure}}::h4a286d7e6e47be58 (0x5616e458e93f)
   1: rust_panic_with_hook (0x5616e46c4f58)
             at src/libstd/panicking.rs:482
   2: std::panicking::begin_panic::hc450aabeec391b37 (0x5616e3d99c44)
   3: <srml_executive::Executive<System, Block, Context, Payment, AllModules>>::execute_block::hdaab6e95de515317 (0x5616e3dc7b95)
   4: robonomics_runtime::api::dispatch::h39c00d5eb8199879 (0x5616e3d9db4e)
   5: std::panicking::try::do_call::he067d85bd1b9c365 (0x5616e39f7671)
   6: __rust_maybe_catch_panic (0x5616e46cae59)
             at src/libpanic_unwind/lib.rs:87
   7: substrate_executor::native_executor::safe_call::h2f93d82fdc1eb9e9 (0x5616e3c19f52)
   8: <std::thread::local::LocalKey<T>>::with::h7082219b6a41aea5 (0x5616e3975a86)
   9: <robonomics::service::Executor as substrate_executor::native_executor::NativeExecutionDispatch>::dispatch::h822b02437272318f (0x5616e38a33e4)
  10: <std::thread::local::LocalKey<T>>::with::hb59f04e4b46da560 (0x5616e3982a65)
  11: <substrate_state_machine::StateMachine<'a, H, B, T, Exec>>::execute_aux::h68a585992d9c0312 (0x5616e39a2e65)
  12: <substrate_state_machine::StateMachine<'a, H, B, T, Exec>>::execute_call_with_native_else_wasm_strategy::hadcd2b2a497bc8a6 (0x5616e39d80e2)
  13: <substrate_state_machine::StateMachine<'a, H, B, T, Exec>>::execute_using_consensus_failure_handler::h851b2e3ba57afdad (0x5616e39c6028)
  14: <substrate_client::call_executor::LocalCallExecutor<B, E> as substrate_client::call_executor::CallExecutor<Block, substrate_primitives::hasher::blake2::Blake2Hasher>>::call_at_state::h55e4abda48a45b83 (0x5616e3a4f0d4)
  15: <substrate_client::client::Client<B, E, Block, RA>>::lock_import_and_run::{{closure}}::h0710a05f576000a6 (0x5616e3d7d7c6)
  16: <substrate_client::client::Client<B, E, Block, RA> as substrate_consensus_common::block_import::BlockImport<Block>>::import_block::h127ec37f672f0538 (0x5616e3d399f6)
  17: <substrate_finality_grandpa::import::GrandpaBlockImport<B, E, Block, RA, PRA> as substrate_consensus_common::block_import::BlockImport<Block>>::import_block::hc277d9f4fff6f031 (0x5616e385b625)
  18: <substrate_consensus_common::import_queue::BlockImportWorker<B, V>>::import_a_batch_of_blocks::h4f23ccfe356202c1 (0x5616e38e8538)
  19: std::sys_common::backtrace::__rust_begin_short_backtrace::h8afdef2506739c56 (0x5616e387319e)
  20: std::panicking::try::do_call::hfb79a6c7a63d7d11 (0x5616e39f770d)
  21: __rust_maybe_catch_panic (0x5616e46cae59)
             at src/libpanic_unwind/lib.rs:87
  22: <F as alloc::boxed::FnBox<A>>::call_box::hab6cb353675e64c6 (0x5616e3b54efe)
  23: call_once<(),()> (0x5616e46ca1ed)
             at /rustc/f66e4697ae286985ddefc53c3a047614568458bb/src/liballoc/boxed.rs:749
      start_thread
             at src/libstd/sys_common/thread.rs:14
      thread_start
             at src/libstd/sys/unix/thread.rs:81
  24: start_thread (0x7fe62f6536da)
  25: __clone (0x7fe62f16488e)
  26: <unknown> (0x0)

Thread 'ImportQueueWorker' panicked at 'Storage root must match that calculated.', /home/ensrationis/.cargo/git/checkouts/substrate-7e08433d4c370a21/4cbda5d/srml/executive/src/lib.rs:214

This is a bug. Please report it at:

	https://github.com/airalab/substrate-node-robonomics/issues
```

**Comment by akru** [comment]
Looks like substrate bug, try to run with “—pruning archive”

**Comment by ensrationis** [comment]
ensrationis@razer:~$ robonomics --bootnodes /ip4/164.132.111.49/tcp/30333/p2p/QmbPgV4iTsWHhrZDTPU5g1YtxJ11PcGC3f9oMTaNLUvJ6m --name EnsRazer --pruning archive
2019-03-13 12:30:47 Robonomics Node
2019-03-13 12:30:47   version 0.8.0-ed07386-x86_64-linux-gnu
2019-03-13 12:30:47   by Airalab <research@aira.life>, 2018, 2019
2019-03-13 12:30:47 Chain specification: Robonomics
2019-03-13 12:30:47 Node name: EnsRazer
2019-03-13 12:30:47 Roles: FULL
2019-03-13 12:30:47 Best block: #10408
2019-03-13 12:30:47 Local node address is: /ip4/0.0.0.0/tcp/30333/p2p/QmPfyDnvVShsJYAYa9L3jWJ3gR6GbevJibnccbLSd2EdBv
2019-03-13 12:30:47 Kademlia random query has yielded empty results
2019-03-13 12:30:47 Listening for new connections on 127.0.0.1:9944.
2019-03-13 12:30:48 Failed to write to trie: Database missing expected key: 0x8b9689865ec389991881ee5ae1d09e570fd16ce131e0fbf1c0c9cd5ed2645579
Hash: given=e7e293aa419c0e8370e63ae4e0ed7134f24462889c8cdaea4be15d6513fa46f1, expected=9a18b9b3ce229634c1e7b615b7b8a2bac357503bef68c495079dbbe4c882f399

====================

stack backtrace:
   0: substrate_panic_handler::set::{{closure}}::h4a286d7e6e47be58 (0x55a510d9093f)
   1: rust_panic_with_hook (0x55a510ec6f58)
             at src/libstd/panicking.rs:482
   2: std::panicking::begin_panic::hc450aabeec391b37 (0x55a51059bc44)
   3: <srml_executive::Executive<System, Block, Context, Payment, AllModules>>::execute_block::hdaab6e95de515317 (0x55a5105c9b95)
   4: robonomics_runtime::api::dispatch::h39c00d5eb8199879 (0x55a51059fb4e)
   5: std::panicking::try::do_call::he067d85bd1b9c365 (0x55a5101f9671)
   6: __rust_maybe_catch_panic (0x55a510ecce59)
             at src/libpanic_unwind/lib.rs:87
   7: substrate_executor::native_executor::safe_call::h2f93d82fdc1eb9e9 (0x55a51041bf52)
   8: <std::thread::local::LocalKey<T>>::with::h7082219b6a41aea5 (0x55a510177a86)
   9: <robonomics::service::Executor as substrate_executor::native_executor::NativeExecutionDispatch>::dispatch::h822b02437272318f (0x55a5100a53e4)
  10: <std::thread::local::LocalKey<T>>::with::hb59f04e4b46da560 (0x55a510184a65)
  11: <substrate_state_machine::StateMachine<'a, H, B, T, Exec>>::execute_aux::h68a585992d9c0312 (0x55a5101a4e65)
  12: <substrate_state_machine::StateMachine<'a, H, B, T, Exec>>::execute_call_with_native_else_wasm_strategy::hadcd2b2a497bc8a6 (0x55a5101da0e2)
  13: <substrate_state_machine::StateMachine<'a, H, B, T, Exec>>::execute_using_consensus_failure_handler::h851b2e3ba57afdad (0x55a5101c8028)
  14: <substrate_client::call_executor::LocalCallExecutor<B, E> as substrate_client::call_executor::CallExecutor<Block, substrate_primitives::hasher::blake2::Blake2Hasher>>::call_at_state::h55e4abda48a45b83 (0x55a5102510d4)
  15: <substrate_client::client::Client<B, E, Block, RA>>::lock_import_and_run::{{closure}}::h0710a05f576000a6 (0x55a51057f7c6)
  16: <substrate_client::client::Client<B, E, Block, RA> as substrate_consensus_common::block_import::BlockImport<Block>>::import_block::h127ec37f672f0538 (0x55a51053b9f6)
  17: <substrate_finality_grandpa::import::GrandpaBlockImport<B, E, Block, RA, PRA> as substrate_consensus_common::block_import::BlockImport<Block>>::import_block::hc277d9f4fff6f031 (0x55a51005d625)
  18: <substrate_consensus_common::import_queue::BlockImportWorker<B, V>>::import_a_batch_of_blocks::h4f23ccfe356202c1 (0x55a5100ea538)
  19: std::sys_common::backtrace::__rust_begin_short_backtrace::h8afdef2506739c56 (0x55a51007519e)
  20: std::panicking::try::do_call::hfb79a6c7a63d7d11 (0x55a5101f970d)
  21: __rust_maybe_catch_panic (0x55a510ecce59)
             at src/libpanic_unwind/lib.rs:87
  22: <F as alloc::boxed::FnBox<A>>::call_box::hab6cb353675e64c6 (0x55a510356efe)
  23: call_once<(),()> (0x55a510ecc1ed)
             at /rustc/f66e4697ae286985ddefc53c3a047614568458bb/src/liballoc/boxed.rs:749
      start_thread
             at src/libstd/sys_common/thread.rs:14
      thread_start
             at src/libstd/sys/unix/thread.rs:81
  24: start_thread (0x7f80672286da)
  25: __clone (0x7f8066d3988e)
  26: <unknown> (0x0)

Thread 'ImportQueueWorker' panicked at 'Storage root must match that calculated.', /home/ensrationis/.cargo/git/checkouts/substrate-7e08433d4c370a21/4cbda5d/srml/executive/src/lib.rs:214

This is a bug. Please report it at:

	https://github.com/airalab/substrate-node-robonomics/issues

**Comment by akru** [comment]
Cleanup database before

**Comment by ensrationis** [comment]
After cleanup sync started correct:

ensrationis@razer:~$ rm -rf ~/.local/share/robonomics/
ensrationis@razer:~$ robonomics --name EnsRazer
2019-03-14 14:43:21 Robonomics Node
2019-03-14 14:43:21   version 0.8.0-1ac312f-x86_64-linux-gnu
2019-03-14 14:43:21   by Airalab <research@aira.life>, 2018, 2019
2019-03-14 14:43:21 Chain specification: Robonomics
2019-03-14 14:43:21 Node name: EnsRazer
2019-03-14 14:43:21 Roles: FULL
2019-03-14 14:43:21 Generated a new keypair: 8138d4701e1cd19c8772272d3d9f976167eb8447b7c4041c8e9baa6fbddfb4d7 (5Ez8v6br...)
2019-03-14 14:43:22 Initialising Genesis block/state (state: 0x8448…dfc7, header-hash: 0xa7f1…902e)
2019-03-14 14:43:22 Loaded block-time = 4 seconds from genesis on first-launch
2019-03-14 14:43:22 Loading GRANDPA authority set from genesis on what appears to be first startup.
2019-03-14 14:43:22 Best block: #0
2019-03-14 14:43:22 Local node address is: /ip4/0.0.0.0/tcp/30333/p2p/QmcbmrZxnad4cHNgrQk33HUJmV5vQbGzwT95EUx9PpqxQE
2019-03-14 14:43:22 Listening for new connections on 127.0.0.1:9944.
2019-03-14 14:43:23 Applying authority set change scheduled at block #15
2019-03-14 14:43:23 Applying GRANDPA set change to new set [(5CKhj6NsXY9exr2oCwK2t3v1cfXyWqg9qmAQ2LTM1psyZ6VR (0b703dcc…5f1e), 1), (5DAirazvxYkdNUCQJY8uGz2KdSUJnEYzPRDb78ss1S8ewFQv (30d31143…1cca), 1), (5Dakru9P3kCScVXgoU2pN8dQU3US178msVxUatD122affWFt (4327b538…5b0e), 1)]
2019-03-14 14:43:23 Imported justification for block #15 that triggers command Changing authorities, signalling voter.
2019-03-14 14:43:24 Banning 6 because "Peer is on different chain (our genesis: 0xa7f1…902e theirs: 0xfb57…343d)"
2019-03-14 14:43:24 Banned PeerId(QmVhXwTBoWHUCfWeXuhndyj4FoNaoyN68kNki4p7vGBjpE) (#6, Dialer { address: "/ip4/116.203.53.65/tcp/30333" }, Some("robonomics-node/v0.7.1-073fd6b-x86_64-linux-gnu (unknown)"))
2019-03-14 14:43:27 Syncing, target=#35988 (5 peers), best: #871 (0x63bf…c73a), finalized #15 (0x9492…01c6), ⬇ 135.2kiB/s ⬆ 5.3kiB/s
Runtime: balance too low to send value
Runtime: not a controller
2019-03-14 14:43:31 Applying authority set change scheduled at block #1800
2019-03-14 14:43:31 Applying GRANDPA set change to new set [(5F15DkQbxPYSz9rYc2vcu25ASwQ1geZpiQq4my6m3r6zAHjz (81efa271…439e), 1), (5CKhj6NsXY9exr2oCwK2t3v1cfXyWqg9qmAQ2LTM1psyZ6VR (0b703dcc…5f1e), 1), (5DAirazvxYkdNUCQJY8uGz2KdSUJnEYzPRDb78ss1S8ewFQv (30d31143…1cca), 1), (5Dakru9P3kCScVXgoU2pN8dQU3US178msVxUatD122affWFt (4327b538…5b0e), 1)]
2019-03-14 14:43:31 Imported justification for block #1800 that triggers command Changing authorities, signalling voter.
2019-03-14 14:43:31 Applying authority set change scheduled at block #1839
2019-03-14 14:43:31 Applying GRANDPA set change to new set [(5CKhj6NsXY9exr2oCwK2t3v1cfXyWqg9qmAQ2LTM1psyZ6VR (0b703dcc…5f1e), 1), (5DAirazvxYkdNUCQJY8uGz2KdSUJnEYzPRDb78ss1S8ewFQv (30d31143…1cca), 1), (5Dakru9P3kCScVXgoU2pN8dQU3US178msVxUatD122affWFt (4327b538…5b0e), 1)]
2019-03-14 14:43:31 Imported justification for block #1839 that triggers command Changing authorities, signalling voter.
2019-03-14 14:43:32 Syncing 201.6 bps, target=#35989 (5 peers), best: #1879 (0x9282…5572), finalized #1839 (0x0013…f1b1), ⬇ 33.6kiB/s ⬆ 1.5kiB/s
2019-03-14 14:43:39 Syncing 231.7 bps, target=#35991 (8 peers), best: #3584 (0x57e9…43bd), finalized #1839 (0x0013…f1b1), ⬇ 82.4kiB/s ⬆ 2.1kiB/s
2019-03-14 14:43:44 Syncing 211.8 bps, target=#35993 (8 peers), best: #4643 (0xf362…e1e7), finalized #1839 (0x0013…f1b1), ⬇ 4.7kiB/s ⬆ 3.1kiB/s
2019-03-14 14:43:49 Syncing 186.6 bps, target=#35994 (7 peers), best: #5576 (0xc9a1…9ad9), finalized #1839 (0x0013…f1b1), ⬇ 101.5kiB/s ⬆ 1.4kiB/s

====+++++===============
 but after 30k blocks:


ensrationis@razer:~$ robonomics --name EnsRazer
2019-03-14 14:41:26 Robonomics Node
2019-03-14 14:41:26   version 0.8.0-1ac312f-x86_64-linux-gnu
2019-03-14 14:41:26   by Airalab <research@aira.life>, 2018, 2019
2019-03-14 14:41:26 Chain specification: Robonomics
2019-03-14 14:41:26 Node name: EnsRazer
2019-03-14 14:41:26 Roles: FULL
2019-03-14 14:41:26 Best block: #35888
2019-03-14 14:41:26 Local node address is: /ip4/0.0.0.0/tcp/30333/p2p/QmYDRzLSuJ49iUBeatqNfQojh4PkUS1WsJ7kdydgeukikg
2019-03-14 14:41:26 Kademlia random query has yielded empty results
2019-03-14 14:41:26 Listening for new connections on 127.0.0.1:9944.

====================

stack backtrace:
   0: substrate_panic_handler::set::{{closure}}::h4a286d7e6e47be58 (0x55c172d98d5f)
   1: rust_panic_with_hook (0x55c172ecf358)
             at src/libstd/panicking.rs:482
   2: continue_panic_fmt (0x55c172ecedf1)
             at src/libstd/panicking.rs:385
   3: rust_begin_unwind (0x55c172ececd5)
   4: panic_fmt (0x55c172ee960c)
             at src/libcore/panicking.rs:85
   5: core::result::unwrap_failed::hf63d95e5113cd435 (0x55c1724ba02d)
   6: <substrate_state_machine::ext::Ext<'a, H, B, T> as substrate_state_machine::Externalities<H>>::storage::h73c40e98b0fc9ef2 (0x55c17253e134)
   7: <std::thread::local::LocalKey<T>>::with::h7b042108ec9e4c5b (0x55c172d7a872)
   8: sr_io::read_storage::ha7605d71fc518fd6 (0x55c172d7a46b)
   9: <(R, S) as srml_session::OnSessionChange<T>>::on_session_change::hbbb66929c00795e1 (0x55c1725c53da)
  10: <srml_session::Module<T> as sr_primitives::traits::OnFinalise<<T as srml_system::Trait>::BlockNumber>>::on_finalise::h9f6f9dabafd0fcac (0x55c1725ce34d)
  11: <(O, P, Q, R, S, T, U, V, W, X, Y, Z) as sr_primitives::traits::OnFinalise<Number>>::on_finalise::h345089b879758e2c (0x55c1725d4167)
  12: <srml_executive::Executive<System, Block, Context, Payment, AllModules>>::execute_block::hdaab6e95de515317 (0x55c1725d190e)
  13: robonomics_runtime::api::dispatch::h39c00d5eb8199879 (0x55c1725a7f6e)
  14: std::panicking::try::do_call::he067d85bd1b9c365 (0x55c172201501)
  15: __rust_maybe_catch_panic (0x55c172ed5259)
             at src/libpanic_unwind/lib.rs:87
  16: substrate_executor::native_executor::safe_call::h2f93d82fdc1eb9e9 (0x55c172423de2)
  17: <std::thread::local::LocalKey<T>>::with::h7082219b6a41aea5 (0x55c17217f916)
  18: <robonomics::service::Executor as substrate_executor::native_executor::NativeExecutionDispatch>::dispatch::h822b02437272318f (0x55c1720ad3e4)
  19: <std::thread::local::LocalKey<T>>::with::hb59f04e4b46da560 (0x55c17218c8f5)
  20: <substrate_state_machine::StateMachine<'a, H, B, T, Exec>>::execute_aux::h68a585992d9c0312 (0x55c1721accf5)
  21: <substrate_state_machine::StateMachine<'a, H, B, T, Exec>>::execute_call_with_native_else_wasm_strategy::hadcd2b2a497bc8a6 (0x55c1721e1f72)
  22: <substrate_state_machine::StateMachine<'a, H, B, T, Exec>>::execute_using_consensus_failure_handler::h851b2e3ba57afdad (0x55c1721cfeb8)
  23: <substrate_client::call_executor::LocalCallExecutor<B, E> as substrate_client::call_executor::CallExecutor<Block, substrate_primitives::hasher::blake2::Blake2Hasher>>::call_at_state::h55e4abda48a45b83 (0x55c172258f64)
  24: <substrate_client::client::Client<B, E, Block, RA>>::lock_import_and_run::{{closure}}::h0710a05f576000a6 (0x55c172589c56)
  25: <substrate_client::client::Client<B, E, Block, RA> as substrate_consensus_common::block_import::BlockImport<Block>>::import_block::h127ec37f672f0538 (0x55c172544d76)
  26: <substrate_finality_grandpa::import::GrandpaBlockImport<B, E, Block, RA, PRA> as substrate_consensus_common::block_import::BlockImport<Block>>::import_block::hc277d9f4fff6f031 (0x55c172065625)
  27: <substrate_consensus_common::import_queue::BlockImportWorker<B, V>>::import_a_batch_of_blocks::h4f23ccfe356202c1 (0x55c1720f23c8)
  28: std::sys_common::backtrace::__rust_begin_short_backtrace::h8afdef2506739c56 (0x55c17207d19e)
  29: std::panicking::try::do_call::hfb79a6c7a63d7d11 (0x55c17220159d)
  30: __rust_maybe_catch_panic (0x55c172ed5259)
             at src/libpanic_unwind/lib.rs:87
  31: <F as alloc::boxed::FnBox<A>>::call_box::hab6cb353675e64c6 (0x55c17235ed8e)
  32: call_once<(),()> (0x55c172ed45ed)
             at /rustc/f66e4697ae286985ddefc53c3a047614568458bb/src/liballoc/boxed.rs:749
      start_thread
             at src/libstd/sys_common/thread.rs:14
      thread_start
             at src/libstd/sys/unix/thread.rs:81
  33: start_thread (0x7fb0c12ab6da)
  34: __clone (0x7fb0c0dbc88e)
  35: <unknown> (0x0)

Thread 'ImportQueueWorker' panicked at 'Externalities not allowed to fail within runtime: "Trie lookup error: Database missing expected key: 0xbb487b9d409bce4e7627c2f119d4754dc179f9430d81eb8c9da4bd87a5f433cc"', src/libcore/result.rs:997

This is a bug. Please report it at:

	https://github.com/airalab/substrate-node-robonomics/issues

**Comment by ensrationis** [comment]
A few second ago I repeated rm and start sync from beginning and now ok. I will track next 2 days and come back.

**Comment by akru** [comment]
Upstream discussion here: 
https://github.com/paritytech/substrate/issues/1733

**Comment by meltausorion** [comment]
On v0.8.1
new sync
https://pastebin.com/Z2ri4GiM

if I restart
https://pastebin.com/mZWBhukj
