### ISSUE TITLE
Thread 'ImportQueueWorker' panicked at 'Externalities not allowed to fail within runtime: "Trie lookup error: Database missing expected key

### ISSUE THREAD

**Issue by ensrationis** [airalab/substrate-node-robonomics#17]
**Before starting I clean db in ~/local/share/robonomics and sync started correctly. Sync stuck at block #73673 with the next error:**

2019-03-16 04:47:50 Failed to write to trie: Database missing expected key: 0x018624c2b07dfa641b0d12dc20f15c0914fa87d6bef338d5b3ac86bbeed1e9b2
Hash not equal
14f05e37949d75681ef45e65e54adb33529a61338c3fed18c98c949ea3520938
46b4d38f6e9f2f2f14148af98f9a6d2141dda5b31ebb6d4a5695efb93a9e3fd8
/home/akru/.cargo/git/checkouts/substrate-7e08433d4c370a21/4cbda5d/srml/executive/src/lib.rs
214
3
2019-03-16 04:47:51 Failed to write to trie: Database missing expected key: 0x018624c2b07dfa641b0d12dc20f15c0914fa87d6bef338d5b3ac86bbeed1e9b2
Hash: given=14f05e37949d75681ef45e65e54adb33529a61338c3fed18c98c949ea3520938, expected=46b4d38f6e9f2f2f14148af98f9a6d2141dda5b31ebb6d4a5695efb93a9e3fd8

====================

stack backtrace:
   0: substrate_panic_handler::set::{{closure}}::h8c172536ddeed52c (0x55de0cc19140)
   1: std::panicking::rust_panic_with_hook::h744417edfe714d72 (0x55de0cd54329)
             at src/libstd/panicking.rs:482
   2: std::panicking::begin_panic::h070ef5ed16943c11 (0x55de0c413924)
   3: <srml_executive::Executive<System, Block, Context, Payment, AllModules>>::execute_block::h2d94eb8736b42088 (0x55de0c4519e4)
   4: robonomics_runtime::api::dispatch::h624caf9d0d3a021c (0x55de0c41a565)
   5: std::panicking::try::do_call::hfdd6cab3fcd94321 (0x55de0c0ed221)
   6: __rust_maybe_catch_panic (0x55de0cd5a209)
             at src/libpanic_unwind/lib.rs:92
   7: substrate_executor::native_executor::safe_call::h69905fb79dcb1747 (0x55de0c1b78b2)
   8: <std::thread::local::LocalKey<T>>::with::h105b020622452a54 (0x55de0bf7400d)
   9: <robonomics::service::Executor as substrate_executor::native_executor::NativeExecutionDispatch>::dispatch::h95fb089fdaa59576 (0x55de0c196c8c)
  10: <std::thread::local::LocalKey<T>>::with::hf9842a3c25e96666 (0x55de0bf9a427)
  11: <substrate_state_machine::StateMachine<'a, H, B, T, Exec>>::execute_aux::h195c5af210fbdca1 (0x55de0c01e1c5)
  12: <substrate_state_machine::StateMachine<'a, H, B, T, Exec>>::execute_call_with_native_else_wasm_strategy::hf41040ce91c4c6ee (0x55de0c054482)
  13: <substrate_state_machine::StateMachine<'a, H, B, T, Exec>>::execute_using_consensus_failure_handler::h145667c6e7499ef4 (0x55de0c02a92b)
  14: <substrate_client::call_executor::LocalCallExecutor<B, E> as substrate_client::call_executor::CallExecutor<Block, substrate_primitives::hasher::blake2::Blake2Hasher>>::call_at_state::heb6f8f341b8ca38f (0x55de0c0d1834)
  15: <substrate_client::client::Client<B, E, Block, RA>>::lock_import_and_run::{{closure}}::h750167034bd8e1dd (0x55de0c3f7226)
  16: <substrate_client::client::Client<B, E, Block, RA> as substrate_consensus_common::block_import::BlockImport<Block>>::import_block::h49d3857e6d81d31f (0x55de0c3b61d6)
  17: <substrate_finality_grandpa::import::GrandpaBlockImport<B, E, Block, RA, PRA> as substrate_consensus_common::block_import::BlockImport<Block>>::import_block::h3fbe10fd3432bb85 (0x55de0c157fff)
  18: <substrate_consensus_common::import_queue::BlockImportWorker<B, V>>::import_a_batch_of_blocks::h65d230882d1f8939 (0x55de0bf51f0c)
  19: std::sys_common::backtrace::__rust_begin_short_backtrace::h6b4a05d70f0c2429 (0x55de0c1671ce)
  20: std::panicking::try::do_call::h1658773b6f2ccd99 (0x55de0c0ec4fd)
  21: __rust_maybe_catch_panic (0x55de0cd5a209)
             at src/libpanic_unwind/lib.rs:92
  22: <F as alloc::boxed::FnBox<A>>::call_box::h9dd5e7044449507c (0x55de0c1d779e)
  23: <alloc::boxed::Box<(dyn alloc::boxed::FnBox<A, Output=R> + 'a)> as core::ops::function::FnOnce<A>>::call_once::h2263113ac6678036 (0x55de0cd5957d)
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858/src/liballoc/boxed.rs:744
      std::sys_common::thread::start_thread::h7f66efdea8634396
             at src/libstd/sys_common/thread.rs:14
      std::sys::unix::thread::Thread::new::thread_start::h6fb76bcf544b6181
             at src/libstd/sys/unix/thread.rs:81
  24: start_thread (0x7fcb899cf6da)
  25: __clone (0x7fcb894e088e)
  26: <unknown> (0x0)

Thread 'ImportQueueWorker' panicked at 'Storage root must match that calculated.', /home/ensrationis/.cargo/git/checkouts/substrate-7e08433d4c370a21/4cbda5d/srml/executive/src/lib.rs:214

This is a bug. Please report it at:

	https://github.com/airalab/substrate-node-robonomics/issues

2019-03-16 04:47:51 Dropping 1 because "Verification failed: Error(Execution(Error(Wasmi(Trap(Trap { kind: MemoryAccessOutOfBounds })), State { next_error: None, backtrace: InternalBacktrace { backtrace: None } })), State { next_error: None, backtrace: InternalBacktrace { backtrace: None } })"
2019-03-16 04:47:51 Dropping 4 because "Verification failed: Error(Execution(Error(Wasmi(Trap(Trap { kind: MemoryAccessOutOfBounds })), State { next_error: None, backtrace: InternalBacktrace { backtrace: None } })), State { next_error: None, backtrace: InternalBacktrace { backtrace: None } })"
2019-03-16 04:47:51 Dropping 9 because "Verification failed: Error(Execution(Error(Wasmi(Trap(Trap { kind: MemoryAccessOutOfBounds })), State { next_error: None, backtrace: InternalBacktrace { backtrace: None } })), State { next_error: None, backtrace: InternalBacktrace { backtrace: None } })"
2019-03-16 04:47:52 Dropping 7 because "Verification failed: Error(Execution(Error(Wasmi(Trap(Trap { kind: MemoryAccessOutOfBounds })), State { next_error: None, backtrace: InternalBacktrace { backtrace: None } })), State { next_error: None, backtrace: InternalBacktrace { backtrace: None } })"
2019-03-16 04:47:53 Dropping 2 because "Verification failed: Error(Execution(Error(Wasmi(Trap(Trap { kind: MemoryAccessOutOfBounds })), State { next_error: None, backtrace: InternalBacktrace { backtrace: None } })), State { next_error: None, backtrace: InternalBacktrace { backtrace: None } })"
2019-03-16 04:47:53 Dropping 8 because "Verification failed: Error(Execution(Error(Wasmi(Trap(Trap { kind: MemoryAccessOutOfBounds })), State { next_error: None, backtrace: InternalBacktrace { backtrace: None } })), State { next_error: None, backtrace: InternalBacktrace { backtrace: None } })"
2019-03-16 04:47:53 Syncing, target=#73848 (4 peers), best: #73673 (0xf840…c1a7), finalized #73654 (0x151b…c636), ⬇ 123.6kiB/s ⬆ 2.3kiB/s
2019-03-16 04:47:54 Dropping 10 because "Verification failed: Error(Execution(Error(Wasmi(Trap(Trap { kind: MemoryAccessOutOfBounds })), State { next_error: None, backtrace: InternalBacktrace { backtrace: None } })), State { next_error: None, backtrace: InternalBacktrace { backtrace: None } })"
2019-03-16 04:47:55 Dropping 3 because "Verification failed: Error(Execution(Error(Wasmi(Trap(Trap { kind: MemoryAccessOutOfBounds })), State { next_error: None, backtrace: InternalBacktrace { backtrace: None } })), State { next_error: None, backtrace: InternalBacktrace { backtrace: None } })"
2019-03-16 04:47:57 Dropping 6 because "Verification failed: Error(Execution(Error(Wasmi(Trap(Trap { kind: MemoryAccessOutOfBounds })), State { next_error: None, backtrace: InternalBacktrace { backtrace: None } })), State { next_error: None, backtrace: InternalBacktrace { backtrace: None } })"
2019-03-16 04:47:58 Idle (1 peers), best: #73673 (0xf840…c1a7), finalized #73654 (0x151b…c636), ⬇ 34.7kiB/s ⬆ 0.9kiB/s
2019-03-16 04:48:01 Dropping 5 because "Verification failed: Error(Execution(Error(Wasmi(Trap(Trap { kind: MemoryAccessOutOfBounds })), State { next_error: None, backtrace: InternalBacktrace { backtrace: None } })), State { next_error: None, backtrace: InternalBacktrace { backtrace: None } })"
2019-03-16 04:48:03 Idle (0 peers), best: #73673 (0xf840…c1a7), finalized #73654 (0x151b…c636), ⬇ 6.1kiB/s ⬆ 0.5kiB/s
2019-03-16 04:48:08 Idle (0 peers), best: #73673 (0xf840…c1a7), finalized #73654 (0x151b…c636), ⬇ 0.5kiB/s ⬆ 0.5kiB/s

**When  I try to restart have the next error:**

ensrationis@ensrationis-01:~$ robonomics --name EnsHQ
2019-03-16 05:06:22 Robonomics Node
2019-03-16 05:06:22   version 0.8.0-16c8a54-x86_64-linux-gnu
2019-03-16 05:06:22   by Airalab <research@aira.life>, 2018, 2019
2019-03-16 05:06:22 Chain specification: Robonomics
2019-03-16 05:06:22 Node name: EnsHQ
2019-03-16 05:06:22 Roles: FULL
2019-03-16 05:06:26 Best block: #73673
2019-03-16 05:06:26 Local node address is: /ip4/0.0.0.0/tcp/30333/p2p/QmTQG2KmtRFAjDQucK6P9Y3J2mx4g7xohsCQEWJbaS8MA1
2019-03-16 05:06:26 Kademlia random query has yielded empty results
2019-03-16 05:06:26 Listening for new connections on 127.0.0.1:9944.

====================

stack backtrace:
   0: substrate_panic_handler::set::{{closure}}::h8c172536ddeed52c (0x556f4911c140)
   1: std::panicking::rust_panic_with_hook::h744417edfe714d72 (0x556f49257329)
             at src/libstd/panicking.rs:482
   2: std::panicking::continue_panic_fmt::h3557b3c3fa21b47b (0x556f49256dd1)
             at src/libstd/panicking.rs:385
   3: rust_begin_unwind (0x556f49256cb5)
             at src/libstd/panicking.rs:312
   4: core::panicking::panic_fmt::h74ee8034b317ceed (0x556f4927199c)
             at src/libcore/panicking.rs:85
   5: core::result::unwrap_failed::h8287afd8ea1e7bf5 (0x556f487b4ed9)
   6: <substrate_state_machine::ext::Ext<'a, H, B, T> as substrate_state_machine::Externalities<H>>::storage::h8552443fdcc283c2 (0x556f488b1334)
   7: <std::thread::local::LocalKey<T>>::with::h9f5371b40d21a095 (0x556f490fde89)
   8: sr_io::read_storage::h07e4931de7237377 (0x556f490fd79b)
   9: <(R, S) as srml_session::OnSessionChange<T>>::on_session_change::h3cfc60f9d42a1790 (0x556f48940a32)
  10: <(O, P, Q, R, S, T, U, V, W, X, Y, Z) as sr_primitives::traits::OnFinalise<Number>>::on_finalise::h864a1253543c4598 (0x556f48949a8e)
  11: <srml_executive::Executive<System, Block, Context, Payment, AllModules>>::execute_block::h2d94eb8736b42088 (0x556f4895432e)
  12: robonomics_runtime::api::dispatch::h624caf9d0d3a021c (0x556f4891d565)
  13: std::panicking::try::do_call::hfdd6cab3fcd94321 (0x556f485f0221)
  14: __rust_maybe_catch_panic (0x556f4925d209)
             at src/libpanic_unwind/lib.rs:92
  15: substrate_executor::native_executor::safe_call::h69905fb79dcb1747 (0x556f486ba8b2)
  16: <std::thread::local::LocalKey<T>>::with::h105b020622452a54 (0x556f4847700d)
  17: <robonomics::service::Executor as substrate_executor::native_executor::NativeExecutionDispatch>::dispatch::h95fb089fdaa59576 (0x556f48699c8c)
  18: <std::thread::local::LocalKey<T>>::with::hf9842a3c25e96666 (0x556f4849d427)
  19: <substrate_state_machine::StateMachine<'a, H, B, T, Exec>>::execute_aux::h195c5af210fbdca1 (0x556f485211c5)
  20: <substrate_state_machine::StateMachine<'a, H, B, T, Exec>>::execute_call_with_native_else_wasm_strategy::hf41040ce91c4c6ee (0x556f48557482)
  21: <substrate_state_machine::StateMachine<'a, H, B, T, Exec>>::execute_using_consensus_failure_handler::h145667c6e7499ef4 (0x556f4852d92b)
  22: <substrate_client::call_executor::LocalCallExecutor<B, E> as substrate_client::call_executor::CallExecutor<Block, substrate_primitives::hasher::blake2::Blake2Hasher>>::call_at_state::heb6f8f341b8ca38f (0x556f485d4834)
  23: <substrate_client::client::Client<B, E, Block, RA>>::lock_import_and_run::{{closure}}::h750167034bd8e1dd (0x556f488fa226)
  24: <substrate_client::client::Client<B, E, Block, RA> as substrate_consensus_common::block_import::BlockImport<Block>>::import_block::h49d3857e6d81d31f (0x556f488b91d6)
  25: <substrate_finality_grandpa::import::GrandpaBlockImport<B, E, Block, RA, PRA> as substrate_consensus_common::block_import::BlockImport<Block>>::import_block::h3fbe10fd3432bb85 (0x556f4865afff)
  26: <substrate_consensus_common::import_queue::BlockImportWorker<B, V>>::import_a_batch_of_blocks::h65d230882d1f8939 (0x556f48454f0c)
  27: std::sys_common::backtrace::__rust_begin_short_backtrace::h6b4a05d70f0c2429 (0x556f4866a1ce)
  28: std::panicking::try::do_call::h1658773b6f2ccd99 (0x556f485ef4fd)
  29: __rust_maybe_catch_panic (0x556f4925d209)
             at src/libpanic_unwind/lib.rs:92
  30: <F as alloc::boxed::FnBox<A>>::call_box::h9dd5e7044449507c (0x556f486da79e)
  31: <alloc::boxed::Box<(dyn alloc::boxed::FnBox<A, Output=R> + 'a)> as core::ops::function::FnOnce<A>>::call_once::h2263113ac6678036 (0x556f4925c57d)
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858/src/liballoc/boxed.rs:744
      std::sys_common::thread::start_thread::h7f66efdea8634396
             at src/libstd/sys_common/thread.rs:14
      std::sys::unix::thread::Thread::new::thread_start::h6fb76bcf544b6181
             at src/libstd/sys/unix/thread.rs:81
  32: start_thread (0x7fdeab5686da)
  33: __clone (0x7fdeab07988e)
  34: <unknown> (0x0)

Thread 'ImportQueueWorker' panicked at 'Externalities not allowed to fail within runtime: "Trie lookup error: Database missing expected key: 0x018624c2b07dfa641b0d12dc20f15c0914fa87d6bef338d5b3ac86bbeed1e9b2"', src/libcore/result.rs:997

This is a bug. Please report it at:

	https://github.com/airalab/substrate-node-robonomics/issues

**Comment by akru** [comment]
Duplicate #13
